<?php
$createTable[11][0] = "CREATE TABLE icp_icons_c4 ([itemId] int NOT NULL PRIMARY KEY,[itemIcon] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemName] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemType] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemDrop] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSell] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemWeight] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemGrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBodyPart] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemPAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemMAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTypeName] varchar(255) COLLATE Latin1_General_CI_AS NULL)";
$tableName[11][0] = "icp_icons_c4";
$createTable[11][1] = "CREATE TABLE icp_icons_classic ([itemId] int NOT NULL PRIMARY KEY,[itemIcon] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemName] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemType] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemDrop] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSell] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemWeight] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemGrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBodyPart] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemPAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemMAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTypeName] varchar(255) COLLATE Latin1_General_CI_AS NULL)";
$tableName[11][1] = "icp_icons_classic";
$createTable[11][2] = "CREATE TABLE icp_icons_essence ([itemId] int NOT NULL PRIMARY KEY,[itemIcon] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemName] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemType] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemDrop] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSell] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemWeight] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemGrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBodyPart] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemPAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemMAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTypeName] varchar(255) COLLATE Latin1_General_CI_AS NULL)";
$tableName[11][2] = "icp_icons_essence";
$createTable[11][3] = "CREATE TABLE icp_icons_freya ([itemId] int NOT NULL PRIMARY KEY,[itemIcon] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemName] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemType] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemDrop] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSell] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemWeight] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemGrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBodyPart] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemPAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemMAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTypeName] varchar(255) COLLATE Latin1_General_CI_AS NULL)";
$tableName[11][3] = "icp_icons_freya";
$createTable[11][4] = "CREATE TABLE icp_icons_god ([itemId] int NOT NULL PRIMARY KEY,[itemIcon] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemName] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemType] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemDrop] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSell] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemWeight] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemGrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBodyPart] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemPAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemMAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTypeName] varchar(255) COLLATE Latin1_General_CI_AS NULL)";
$tableName[11][4] = "icp_icons_god";
$createTable[11][5] = "CREATE TABLE icp_icons_gracia ([itemId] int NOT NULL PRIMARY KEY,[itemIcon] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemName] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemType] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemDrop] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSell] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemWeight] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemGrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBodyPart] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemPAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemMAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTypeName] varchar(255) COLLATE Latin1_General_CI_AS NULL)";
$tableName[11][5] = "icp_icons_gracia";
$createTable[11][6] = "CREATE TABLE icp_icons_high_five ([itemId] int NOT NULL PRIMARY KEY,[itemIcon] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemName] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemType] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemDrop] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSell] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemWeight] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemGrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBodyPart] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemPAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemMAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTypeName] varchar(255) COLLATE Latin1_General_CI_AS NULL)";
$tableName[11][6] = "icp_icons_high_five";
$createTable[11][7] = "CREATE TABLE icp_icons_interlude ([itemId] int NOT NULL PRIMARY KEY,[itemIcon] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemName] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemType] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemDrop] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSell] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemWeight] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemGrade] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBodyPart] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemBSS] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemPAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemMAD] varchar(255) COLLATE Latin1_General_CI_AS NULL,[itemTypeName] varchar(255) COLLATE Latin1_General_CI_AS NULL)";
$tableName[11][7] = "icp_icons_interlude";