<?php
$createTable[7][0] = "CREATE TABLE `icp_droplist_c4` (`mobId` int(11) unsigned NOT NULL DEFAULT '0', `itemId` int(11) unsigned NOT NULL DEFAULT '0', `min` int(11) unsigned NOT NULL DEFAULT '0', `max` int(11) unsigned NOT NULL DEFAULT '0', `sweep` int(1) unsigned NOT NULL DEFAULT '0', `chance` decimal(11,4) unsigned NOT NULL DEFAULT '0.0000', INDEX `key_mobId`(`mobId`) USING BTREE) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[7][0] = "icp_droplist_c4";
$createTable[7][1] = "CREATE TABLE `icp_droplist_classic` (`mobId` int(11) unsigned NOT NULL DEFAULT '0', `itemId` int(11) unsigned NOT NULL DEFAULT '0', `min` int(11) unsigned NOT NULL DEFAULT '0', `max` int(11) unsigned NOT NULL DEFAULT '0', `sweep` int(1) unsigned NOT NULL DEFAULT '0', `chance` decimal(11,4) unsigned NOT NULL DEFAULT '0.0000', INDEX `key_mobId`(`mobId`) USING BTREE) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[7][1] = "icp_droplist_classic";
$createTable[7][2] = "CREATE TABLE `icp_droplist_essence` (`mobId` int(11) unsigned NOT NULL DEFAULT '0', `itemId` int(11) unsigned NOT NULL DEFAULT '0', `min` int(11) unsigned NOT NULL DEFAULT '0', `max` int(11) unsigned NOT NULL DEFAULT '0', `sweep` int(1) unsigned NOT NULL DEFAULT '0', `chance` decimal(11,4) unsigned NOT NULL DEFAULT '0.0000', INDEX `key_mobId`(`mobId`) USING BTREE) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[7][2] = "icp_droplist_essence";
$createTable[7][3] = "CREATE TABLE `icp_droplist_freya` ( `mobId` int(11) unsigned NOT NULL DEFAULT '0', `itemId` int(11) unsigned NOT NULL DEFAULT '0', `min` int(11) unsigned NOT NULL DEFAULT '0', `max` int(11) unsigned NOT NULL DEFAULT '0', `sweep` int(1) NOT NULL DEFAULT '0', `chance` decimal(11,4) unsigned NOT NULL DEFAULT '0.0000', INDEX `key_mobId`(`mobId`) USING BTREE ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
$tableName[7][3] = "icp_droplist_freya";
$createTable[7][4] = "CREATE TABLE `icp_droplist_god` ( `mobId` int(11) unsigned NOT NULL DEFAULT '0', `itemId` int(11) unsigned NOT NULL DEFAULT '0', `min` int(11) unsigned NOT NULL DEFAULT '0', `max` int(11) unsigned NOT NULL DEFAULT '0', `sweep` int(1) NOT NULL DEFAULT '0', `chance` decimal(11,4) unsigned NOT NULL DEFAULT '0.0000', INDEX `key_mobId`(`mobId`) USING BTREE ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
$tableName[7][4] = "icp_droplist_god";
$createTable[7][5] = "CREATE TABLE `icp_droplist_gracia` ( `mobId` int(11) unsigned NOT NULL DEFAULT '0', `itemId` int(11) unsigned NOT NULL DEFAULT '0', `min` int(11) unsigned NOT NULL DEFAULT '0', `max` int(11) unsigned NOT NULL DEFAULT '0', `sweep` int(1) NOT NULL DEFAULT '0', `chance` decimal(11,4) unsigned NOT NULL DEFAULT '0.0000', INDEX `key_mobId`(`mobId`) USING BTREE ) ENGINE=MyISAM DEFAULT CHARSET=latin1";
$tableName[7][5] = "icp_droplist_gracia";
$createTable[7][6] = "CREATE TABLE `icp_droplist_high_five` ( `mobId` int(11) unsigned NOT NULL DEFAULT '0', `itemId` int(11) unsigned NOT NULL DEFAULT '0', `min` int(11) unsigned NOT NULL DEFAULT '0', `max` int(11) unsigned NOT NULL DEFAULT '0', `sweep` int(1) unsigned NOT NULL DEFAULT '0', `chance` int(11) unsigned NOT NULL DEFAULT '0', INDEX `key_mobId`(`mobId`) USING BTREE) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[7][6] = "icp_droplist_high_five";
$createTable[7][7] = "CREATE TABLE `icp_droplist_interlude` ( `mobId` int(11) unsigned NOT NULL DEFAULT '0', `itemId` int(11) unsigned NOT NULL DEFAULT '0', `min` int(11) unsigned NOT NULL DEFAULT '0', `max` int(11) unsigned NOT NULL DEFAULT '0', `sweep` int(1) NOT NULL DEFAULT '0', `chance` decimal(11,4) unsigned NOT NULL DEFAULT '0.0000', INDEX `key_mobId`(`mobId`) USING BTREE) ENGINE=MyISAM DEFAULT CHARSET=latin1";
$tableName[7][7] = "icp_droplist_interlude";