<?php
$createTable[11][0] = "CREATE TABLE `icp_icons_c4` (`itemId` int(6) NOT NULL DEFAULT '0', `itemIcon` varchar(255) DEFAULT NULL, `itemName` varchar(255) DEFAULT NULL, `itemType` varchar(255) DEFAULT NULL, `itemTrade` varchar(255) DEFAULT NULL, `itemDrop` varchar(255) DEFAULT NULL, `itemSell` varchar(255) DEFAULT NULL, `itemWeight` varchar(255) DEFAULT NULL, `itemGrade` varchar(255) DEFAULT NULL, `itemBodyPart` varchar(255) DEFAULT NULL, `itemSS` varchar(255) DEFAULT NULL, `itemBSS` varchar(255) DEFAULT NULL, `itemPAD` varchar(255) DEFAULT NULL, `itemMAD` varchar(255) DEFAULT NULL, `itemTypeName` varchar(255) DEFAULT NULL, PRIMARY KEY (`itemId`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[11][0] = "icp_icons_c4";
$createTable[11][1] = "CREATE TABLE `icp_icons_classic` (`itemId` int(6) NOT NULL DEFAULT '0', `itemIcon` varchar(255) DEFAULT NULL, `itemName` varchar(255) DEFAULT NULL, `itemType` varchar(255) DEFAULT NULL, `itemTrade` varchar(255) DEFAULT NULL, `itemDrop` varchar(255) DEFAULT NULL, `itemSell` varchar(255) DEFAULT NULL, `itemWeight` varchar(255) DEFAULT NULL, `itemGrade` varchar(255) DEFAULT NULL, `itemBodyPart` varchar(255) DEFAULT NULL, `itemSS` varchar(255) DEFAULT NULL, `itemBSS` varchar(255) DEFAULT NULL, `itemPAD` varchar(255) DEFAULT NULL, `itemMAD` varchar(255) DEFAULT NULL, `itemTypeName` varchar(255) DEFAULT NULL, PRIMARY KEY (`itemId`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[11][1] = "icp_icons_classic";
$createTable[11][2] = "CREATE TABLE `icp_icons_essence` (`itemId` int(6) NOT NULL DEFAULT '0', `itemIcon` varchar(255) DEFAULT NULL, `itemName` varchar(255) DEFAULT NULL, `itemType` varchar(255) DEFAULT NULL, `itemTrade` varchar(255) DEFAULT NULL, `itemDrop` varchar(255) DEFAULT NULL, `itemSell` varchar(255) DEFAULT NULL, `itemWeight` varchar(255) DEFAULT NULL, `itemGrade` varchar(255) DEFAULT NULL, `itemBodyPart` varchar(255) DEFAULT NULL, `itemSS` varchar(255) DEFAULT NULL, `itemBSS` varchar(255) DEFAULT NULL, `itemPAD` varchar(255) DEFAULT NULL, `itemMAD` varchar(255) DEFAULT NULL, `itemTypeName` varchar(255) DEFAULT NULL, PRIMARY KEY (`itemId`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[11][2] = "icp_icons_essence";
$createTable[11][3] = "CREATE TABLE `icp_icons_freya` (`itemId` int(6) NOT NULL DEFAULT '0', `itemIcon` varchar(255) DEFAULT NULL, `itemName` varchar(255) DEFAULT NULL, `itemType` varchar(255) DEFAULT NULL, `itemTrade` varchar(255) DEFAULT NULL, `itemDrop` varchar(255) DEFAULT NULL, `itemSell` varchar(255) DEFAULT NULL, `itemWeight` varchar(255) DEFAULT NULL, `itemGrade` varchar(255) DEFAULT NULL, `itemBodyPart` varchar(255) DEFAULT NULL, `itemSS` varchar(255) DEFAULT NULL, `itemBSS` varchar(255) DEFAULT NULL, `itemPAD` varchar(255) DEFAULT NULL, `itemMAD` varchar(255) DEFAULT NULL, `itemTypeName` varchar(255) DEFAULT NULL, PRIMARY KEY (`itemId`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[11][3] = "icp_icons_freya";
$createTable[11][4] = "CREATE TABLE `icp_icons_god` (`itemId` int(6) NOT NULL DEFAULT '0', `itemIcon` varchar(255) DEFAULT NULL, `itemName` varchar(255) DEFAULT NULL, `itemType` varchar(255) DEFAULT NULL, `itemTrade` varchar(255) DEFAULT NULL, `itemDrop` varchar(255) DEFAULT NULL, `itemSell` varchar(255) DEFAULT NULL, `itemWeight` varchar(255) DEFAULT NULL, `itemGrade` varchar(255) DEFAULT NULL, `itemBodyPart` varchar(255) DEFAULT NULL, `itemSS` varchar(255) DEFAULT NULL, `itemBSS` varchar(255) DEFAULT NULL, `itemPAD` varchar(255) DEFAULT NULL, `itemMAD` varchar(255) DEFAULT NULL, `itemTypeName` varchar(255) DEFAULT NULL, PRIMARY KEY (`itemId`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[11][4] = "icp_icons_god";
$createTable[11][5] = "CREATE TABLE `icp_icons_gracia` (`itemId` int(6) NOT NULL DEFAULT '0', `itemIcon` varchar(255) DEFAULT NULL, `itemName` varchar(255) DEFAULT NULL, `itemType` varchar(255) DEFAULT NULL, `itemTrade` varchar(255) DEFAULT NULL, `itemDrop` varchar(255) DEFAULT NULL, `itemSell` varchar(255) DEFAULT NULL, `itemWeight` varchar(255) DEFAULT NULL, `itemGrade` varchar(255) DEFAULT NULL, `itemBodyPart` varchar(255) DEFAULT NULL, `itemSS` varchar(255) DEFAULT NULL, `itemBSS` varchar(255) DEFAULT NULL, `itemPAD` varchar(255) DEFAULT NULL, `itemMAD` varchar(255) DEFAULT NULL, `itemTypeName` varchar(255) DEFAULT NULL, PRIMARY KEY (`itemId`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[11][5] = "icp_icons_gracia";
$createTable[11][6] = "CREATE TABLE `icp_icons_high_five` (`itemId` int(6) NOT NULL DEFAULT '0', `itemIcon` varchar(255) DEFAULT NULL, `itemName` varchar(255) DEFAULT NULL, `itemType` varchar(255) DEFAULT NULL, `itemTrade` varchar(255) DEFAULT NULL, `itemDrop` varchar(255) DEFAULT NULL, `itemSell` varchar(255) DEFAULT NULL, `itemWeight` varchar(255) DEFAULT NULL, `itemGrade` varchar(255) DEFAULT NULL, `itemBodyPart` varchar(255) DEFAULT NULL, `itemSS` varchar(255) DEFAULT NULL, `itemBSS` varchar(255) DEFAULT NULL, `itemPAD` varchar(255) DEFAULT NULL, `itemMAD` varchar(255) DEFAULT NULL, `itemTypeName` varchar(255) DEFAULT NULL, PRIMARY KEY (`itemId`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[11][6] = "icp_icons_high_five";
$createTable[11][7] = "CREATE TABLE `icp_icons_interlude` (`itemId` int(6) NOT NULL DEFAULT '0', `itemIcon` varchar(255) DEFAULT NULL, `itemName` varchar(255) DEFAULT NULL, `itemType` varchar(255) DEFAULT NULL, `itemTrade` varchar(255) DEFAULT NULL, `itemDrop` varchar(255) DEFAULT NULL, `itemSell` varchar(255) DEFAULT NULL, `itemWeight` varchar(255) DEFAULT NULL, `itemGrade` varchar(255) DEFAULT NULL, `itemBodyPart` varchar(255) DEFAULT NULL, `itemSS` varchar(255) DEFAULT NULL, `itemBSS` varchar(255) DEFAULT NULL, `itemPAD` varchar(255) DEFAULT NULL, `itemMAD` varchar(255) DEFAULT NULL, `itemTypeName` varchar(255) DEFAULT NULL, PRIMARY KEY (`itemId`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;";
$tableName[11][7] = "icp_icons_interlude";